classDiagram
  class person {
    first_name
    last_name
    date_of_birth
    national_insurance_number
    email
    address
  }

  person --> address
  class address {
    [click_to_see]
  }


  click address href "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/general/diagrams/address.svg" "Click to see address"