classDiagram
  person --> address
  class address {
    [click_to_see]
  }

  person: first_name
  person: last_name
  person: date_of_birth
  person: national_insurance_number
  person: email
  person: address

  click address href "https://raw.githubusercontent.com/ministryofjustice/laa-schemas/main/prototyping/general/diagrams/address.svg" "Click to see address"