classDiagram
  class laa_application {
    client_details
    case_details
    interests_of_justice
    means_assessment
    evidence
  }

  laa_application --> client_details
  class client_details {
    client
    on_remand
    other_legal_aid_cases
    remanded_date
    partner
    partner_role_in_case
    partner_conflict_of_interest
  }

  client_details --> client
  class client {
    person
  }

  client_details --> partner
  class partner {
    person
  }

  client --> person
  partner --> person
  class person {
    first_name
    last_name
    date_of_birth
    national_insurance_number
    email
    address
  }

  person --> address

  laa_application --> case_details
  class case_details {
    case_type
    court_type
    co_defendant_names
    offence_class
    URN
  }

  laa_application --> interests_of_justice
  class interests_of_justice {
    reason
    justification
  }

  laa_application --> evidence
  class evidence {
    name
    key
    description
    uploaded_date
  }

  laa_application --> means_assessment
  class means_assessment {
    benefits_status
    total_income
    income
    outgoings
    capital
  }

  means_assessment --> benefits_status
  class benefits_status {
    passported
    client_benefits
    partner_benefits
  }

  means_assessment --> income
  class income {
    employment_status
    employed_income
    self_employed_income
    other_income_sources
    dependants
  }

  income --> employed_income
  class employed_income {
    paye
    other_employed_income
    other_employed_income_details
  }

  employed_income --> paye
  class paye {
    paye_date
    paye_amount
    paye_deductions
  }

  income --> self_employed_income
  class self_employed_income {
    business_name
    address
    tax_liability_last_2_years
    total_turnover
    total_drawings
    total_profit
    profit_share
    director_salary
  }

  self_employed_income --> address
  class address {
    address_line_one
    address_line_two
    city
    county
    organisation
    postcode
  }

  income --> other_income_sources
  class other_income_sources {
    income_type
    other_income_amount
    other_income_frequency
  }

  income --> dependants
  class dependants {
    date_of_birth
  }

  means_assessment --> outgoings
  class outgoings {
    outgoing_type
    outgoing_amount
    outgoing_frequency
  }

  means_assessment --> capital
  class capital {
    housing
    vehicle
    savings
    assets
    prohibited_assets
    prohibited_description
  }

  capital --> housing
  class housing {
    property_value
    remaining_mortgage
    ownership_type
    share
  }

  capital --> vehicle
  class vehicle {
    vehicle_value
    remaining_payments
    purchased_over_3_years
    regular_use
  }

  capital --> savings
  class savings {
    savings_type
    savings_value
    savings_description
  }

  capital --> assets
  class assets {
    asset_type
    asset_value
    asset_description
  }
